dist: xenial

language: c

compiler: gcc

addons:
  apt:
    packages:
    - gcc-5
    - cmake
    - check
    - libsubunit-dev

script:
- mkdir -p build
- cd build
- cmake -DENABLE_TESTS=ON ..
- make
- make test
