name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install check
    - name: configure
      run: cmake .
      working-directory: ./build
    - name: make
      run: make
      working-directory: ./build
    - name: make test
      run: make test
      working-directory: ./build
